# docker-compose -f docker-compose.yml -f docker-compose.override.yml up -d

version: "3"

services:

  ############################
  # Web - Reactjs
  ############################
  web:
    image: ${REGISTRY:-vndg}/web:${TAG:-latest}
    build:
      context: .
      dockerfile: src/web/Dockerfile
    depends_on:
      - webapigatewayapp
    networks:
      - coolstore-network

  #######################################
  # webapigateway app 
  #######################################
  webapigatewayapp:
    image: ${REGISTRY:-vndg}/webapigatewayapp:${TAG:-latest}
    build:
      context: .
      dockerfile: src/BFFs/WebApiGateway/Dockerfile
    depends_on:
      - redis
      - identityapp
      - inventoryapp
      - productcatalogapp
      - shoppingcartapp
    networks:
      - coolstore-network

  #######################################
  # identity app
  #######################################
  identityapp:
    image: ${REGISTRY:-vndg}/identityapp:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Identity/IdentityService/Dockerfile
    depends_on:
      - redis
      - postgresql
    networks:
      - coolstore-network

  #######################################
  # inventory app
  #######################################
  inventoryapp:
    image: ${REGISTRY:-vndg}/inventoryapp:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Inventory/InventoryService.Api/Dockerfile
    depends_on:
      - redis
      - postgresql
      - identityapp
    networks:
      - coolstore-network

  #################################################
  # productcatalog app 
  #################################################
  productcatalogapp:
    image: ${REGISTRY:-vndg}/productcatalogapp:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/ProductCatalog/ProductCatalogService.Api/Dockerfile
    depends_on:
      - redis
      - postgresql
      - identityapp
    networks:
      - coolstore-network

  #################################################
  # shoppingcart app 
  #################################################
  shoppingcartapp:
    image: ${REGISTRY:-vndg}/shoppingcartapp:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/ShoppingCart/ShoppingCartService.Api/Dockerfile
    depends_on:
      - redis
      - postgresql
      - identityapp
    networks:
      - coolstore-network

  #################################################
  # sale app 
  #################################################
  saleapp:
    image: ${REGISTRY:-vndg}/saleapp:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Sale/SaleService.Api/Dockerfile
    depends_on:
      - redis
      - postgresql
      - identityapp
    networks:
      - coolstore-network

  ############################
  # PostgresQL component
  ############################
  postgresql:
    image: postgres:11-alpine
    container_name: postgresql
    networks:
      - coolstore-network

  ############################
  # ELK component
  ############################
  # elk:
  #   image: sebp/elk:latest
  #   hostname: elk
  #   container_name: elk
  #   networks:
  #     - coolstore-network

  ############################
  # Zipkin component
  ############################
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    networks:
      - coolstore-network

  ############################
  # Redis state store
  ############################
  redis:
    image: "redis:alpine"
    networks:
      - coolstore-network

networks:
  coolstore-network:
