version: "3"

services:

  ############################
  # PostgresQL component
  ############################
  postgresql:
    image: postgres:11-alpine
    container_name: postgresql
    networks:
      - coolstore-network
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=P@ssw0rd
    ports:
      - "5434:5432"

  ############################
  # Redis state store
  ############################
  redis:
    image: "redis:alpine"
    networks:
      - coolstore-network
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
    ports:
      - "6377:6379"
      
networks:
  coolstore-network:
