version: "3"

services:

  web:
    environment:
      - PORT=3000
      - REACT_APP_AUTHORITY=http://cool-store.ml:5001
      - REACT_APP_API=http://cool-store.ml:5000
    ports:
      - 3000:3000

  webapigatewayapp:
    environment:
      - Services__inventoryapp=http://inventoryapp
      - Services__productcatalogapp=http://productcatalogapp
      - Services__shoppingcartapp=http://shoppingcartapp
      - Services__saleapp=http://saleapp
      - OtelZipkin__Endpoint=http://zipkin:9411/api/v2/spans
    ports:
      - "5000:80"

  identityapp:
    ports:
      - "5001:80"

  inventoryapp:
    environment:
      - ConnectionStrings__postgres=Server=postgresql;Port=5432;Database=postgres;User Id=postgres;Password=P@ssw0rd;
      - ConnectionStrings__redis=redis:6379
      - Redis__Url=redis:6379
      - Authn__Authority=http://identityapp
      - Authn__Audience=http://cool-store.ml/resources
      - OtelZipkin__Endpoint=http://zipkin:9411/api/v2/spans
    ports:
      - "5002:80"

  productcatalogapp:
    restart: always
    environment:
      - ConnectionStrings__postgres=Server=postgresql;Port=5432;Database=postgres;User Id=postgres;Password=P@ssw0rd;
      - ConnectionStrings__redis=redis:6379
      - Redis__Url=redis:6379
      - Authn__Authority=http://identityapp
      - Authn__Audience=http://cool-store.ml/resources
      - OtelZipkin__Endpoint=http://zipkin:9411/api/v2/spans
    ports:
      - "5003:80"

  shoppingcartapp:
    environment:
      - ConnectionStrings__postgres=Server=postgresql;Port=5432;Database=postgres;User Id=postgres;Password=P@ssw0rd;
      - ConnectionStrings__redis=redis:6379
      - Redis__Url=redis:6379
      - Authn__Authority=http://identityapp
      - Authn__Audience=http://cool-store.ml/resources
      - OtelZipkin__Endpoint=http://zipkin:9411/api/v2/spans
    ports:
      - "5004:80"

  saleapp:
    environment:
      - ConnectionStrings__postgres=Server=postgresql;Port=5432;Database=postgres;User Id=postgres;Password=P@ssw0rd;
      - ConnectionStrings__redis=redis:6379
      - Redis__Url=redis:6379
      - Authn__Authority=http://identityapp
      - Authn__Audience=http://cool-store.ml/resources
      - OtelZipkin__Endpoint=http://zipkin:9411/api/v2/spans
    ports:
      - "5005:80"

  postgresql:
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=P@ssw0rd
    ports:
      - "5434:5432"

  # elk:
  #   ports:
  #     - "5601:5601"
  #     - "9200:9200"
  #   expose:
  #     - 5601
  #     - 9200

  zipkin:
    ports:
      - "9411:9411"

  redis:
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
    ports:
      - "6377:6379"
