<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsAspireHost>true</IsAspireHost>
    <UserSecretsId>348a76c6-e449-44b6-abc5-0852f55feb01</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting" Version="8.1.0" />
    <PackageReference Include="Aspire.Hosting.AppHost" Version="8.1.0" />
    <PackageReference Include="Aspire.Hosting.NodeJs" Version="8.1.0" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="8.1.0" />
    <PackageReference Include="Aspire.Hosting.Redis" Version="8.1.0" />
    <PackageReference Include="Aspire.Hosting.RabbitMQ" Version="8.1.0" />
    <PackageReference Include="Aspirant.Hosting" Version="0.0.4" />
    <PackageReference Include="Aspirant.Hosting.Yarp" Version="0.0.4" />
    <PackageReference Include="Yarp.ReverseProxy" Version="2.1.0" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCore.HealthChecks.NpgSql" Version="8.0.1" />
    <PackageReference Include="AspNetCore.HealthChecks.Rabbitmq" Version="8.0.1" />
    <PackageReference Include="AspNetCore.HealthChecks.Redis" Version="8.0.1" />
    <PackageReference Include="AspNetCore.HealthChecks.Uris" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BFFs\WebApiGateway\WebApiGateway.csproj" />
    <ProjectReference Include="..\Services\Identity\IdentityService\IdentityService.csproj" />
    <ProjectReference Include="..\Services\Inventory\InventoryService.Api\InventoryService.Api.csproj" />
    <ProjectReference Include="..\Services\ProductCatalog\ProductCatalogService.Api\ProductCatalogService.Api.csproj" />
    <ProjectReference Include="..\Services\Sale\SaleService.Api\SaleService.Api.csproj" />
    <ProjectReference Include="..\Services\ShoppingCart\ShoppingCartService.Api\ShoppingCartService.Api.csproj" />
    <ProjectReference Include="..\WebUI\BlazorWeb\BlazorWeb\BlazorWeb.Client\BlazorWeb.Client.csproj" />
    <ProjectReference Include="..\WebUI\BlazorWeb\BlazorWeb\BlazorWeb\BlazorWeb.csproj" />
  </ItemGroup>

  <Target Name="RestoreNpm" BeforeTargets="Build" Condition=" '$(DesignTimeBuild)' != 'true' ">
    <ItemGroup>
      <PackageJsons Include="..\*\package.json" />
    </ItemGroup>

    <!-- Install npm packages if node_modules is missing -->
    <Message Importance="Normal" Text="Installing npm packages for %(PackageJsons.RelativeDir)" Condition="!Exists('%(PackageJsons.RootDir)%(PackageJsons.Directory)/node_modules')" />
    <Exec Command="npm install" WorkingDirectory="%(PackageJsons.RootDir)%(PackageJsons.Directory)" Condition="!Exists('%(PackageJsons.RootDir)%(PackageJsons.Directory)/node_modules')" />
  </Target>

</Project>
